# n8n service control:
# docker compose -f docker-compose.n8n.yml up -d    <-- turn on n8n
# docker compose -f docker-compose.n8n.yml down      <-- turn off n8n
# http://localhost:5678
# email: a@a.com
# password: Test123!@#



version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - ./n8n-data:/home/node/.n8n
