name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init Git submodules
        run: |
          git submodule init
          git submodule update --recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Backend & DB
        working-directory: node-express-realworld-example-app
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/conduit?schema=public"
        run: |
          npm install
          npx prisma generate
          npx prisma migrate deploy
          npx nx serve api &
          sleep 10

      - name: Run API Tests
        run: pytest api-tests/tests --html=test-results/api-report.html --self-contained-html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: test-results/api-report.html
